# @package _group_
dataset_name: irmas
root: /home/cezar/Projects/irmas_torch/data/IRMAS
output_dim: 11
input_dim: 1
orig_fs: 44100
classes: ['cel', 'cla', 'flu', 'gac', 'gel', 'org', 'pia', 'sax', 'tru', 'vio', 'voi']