projectname: irmas_torch

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}/${experiment_name}/

defaults:
  - _self_
  # - dataset: irmas
  - experiment/default
  - train/default
  - datamodule/default
  - trainer/default
  - module/default

scheduler_patience: 6
early_stopping_patience: 10

project_name: irmas_torch
task_name: clearml